version: '3'
services:
  front-service:
    build: ./dashboard_analysis
    ports:
      - 3000:3000
  api-server:
    build: ./api_aedas
    environment:
      - MONGO_URI=mongodb://mongodb:27017/api
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"